export enum Colors {
  PRIMARY = 'PRIMARY',
  MAIN_BG = 'MAIN_BG',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',

  NEUTRAL_DARK = 'NEUTRAL_DARK',
  NEUTRAL_GRAY_DARK = 'NEUTRAL_GRAY_DARK',
  NEUTRAL_GRAY = 'NEUTRAL_GRAY',
  NEUTRAL_GRAY_LIGHT = 'NEUTRAL_GRAY_LIGHT',
  NEUTRAL_LIGHT = 'NEUTRAL_LIGHT',

  SEMATIC_RED = 'SEMATIC_RED',
  SEMATIC_BROWN = 'SEMATIC_BROWN',
  SEMATIC_YELLOW = 'SEMATIC_YELLOW',
}

export const COLORS = {
  PRIMARY: '#8F5F43',
  MAIN_BG: '#FFFFFF',
  SUCCESS: '#3ebf35',
  ERROR: '#e20e00',

  NEUTRAL_DARK: '#272422',
  NEUTRAL_GRAY_DARK: '#9D9EA3',
  NEUTRAL_GRAY: '#C9C9C9',
  NEUTRAL_GRAY_LIGHT: '#F2F2F2',
  NEUTRAL_LIGHT: '#FFFFFF',

  SEMATIC_RED: '#DA2C2C',
  SEMATIC_BROWN: '#390B12',
  SEMATIC_YELLOW: '#FFC600',
};

export enum TextSize {
  small = 12,
  medium = 16,
  large = 18,
  xlarge = 20,
  extraLarge = 24,
}

export enum TextFamily {
  REGULAR = 'Muli-Regular',
  BOLD = 'Muli-Bold',
  SEMIBOLD = 'Muli-SemiBold',
}
